apiVersion: apps/v1          #A
kind: Deployment             #A
metadata:
  name: guestbook-deploy     #A
spec:
  template:
    spec:
      containers:
      - name: guestbook      #B
        env:                 #C
        - name: DEBUG
          value: "true"

